/*********************************************************************
*  #### Twitter Post Fetcher v18.0.3 ####
*  Coded by Jason Mayes 2015. A present to all the developers out there.
*  www.jasonmayes.com
*  Please keep this disclaimer with my code if you use it. Thanks. :-)
*  Got feedback or questions, ask here:
*  http://www.jasonmayes.com/projects/twitterApi/
*  Github: https://github.com/jasonmayes/Twitter-Post-Fetcher
*  Updates will be posted to this site.
*********************************************************************/
(function(y,l){"function"===typeof define&&define.amd?define([],l):"object"===typeof exports?module.exports=l():l()})(this,function(){function y(a){if(null===A){for(var h=a.length,c=0,f=document.getElementById(H),g="<ul>";c<h;)g+="<li>"+a[c]+"</li>",c++;f.innerHTML=g+"</ul>"}else A(a)}function l(a){return a.replace(/<b[^>]*>(.*?)<\/b>/gi,function(a,c){return c}).replace(/class="(?!(tco-hidden|tco-display|tco-ellipsis))+.*?"|data-query-source=".*?"|dir=".*?"|rel=".*?"/gi,"")}function I(a){a=a.getElementsByTagName("a");
for(var h=a.length-1;0<=h;h--)a[h].setAttribute("target","_blank"),a[h].setAttribute("rel","noopener")}function p(a,h){for(var c=[],f=new RegExp("(^| )"+h+"( |$)"),g=a.getElementsByTagName("*"),k=0,d=g.length;k<d;k++)f.test(g[k].className)&&c.push(g[k]);return c}function u(a){if(void 0!==a&&0<=a.innerHTML.indexOf("data-image")){if(a=a.innerHTML.match(/data-image="([A-z0-9]+:\/\/[A-z0-9]+\.[A-z0-9]+\.[A-z0-9]+\/[A-z0-9]+\/[A-z0-9\-]+)"/ig))for(var h=0;h<a.length;h++)a[h]=a[h].match(/data-image="([A-z0-9]+:\/\/[A-z0-9]+\.[A-z0-9]+\.[A-z0-9]+\/[A-z0-9]+\/[A-z0-9\-]+)"/i)[1],
a[h]=decodeURIComponent(a[h])+".jpg";return a}}var H="",m=20,J=!0,z=[],B=!1,C=!0,r=!0,D=null,E=!0,F=!0,A=null,K=!0,v=!1,L=!1,w=!0,M=!0,N=!1,n=null,G={fetch:function(a){void 0===a.maxTweets&&(a.maxTweets=20);void 0===a.enableLinks&&(a.enableLinks=!0);void 0===a.showUser&&(a.showUser=!0);void 0===a.showTime&&(a.showTime=!0);void 0===a.dateFunction&&(a.dateFunction="default");void 0===a.showRetweet&&(a.showRetweet=!0);void 0===a.customCallback&&(a.customCallback=null);void 0===a.showInteraction&&(a.showInteraction=
!0);void 0===a.showImages&&(a.showImages=!1);void 0===a.useEmoji&&(a.useEmoji=!1);void 0===a.linksInNewWindow&&(a.linksInNewWindow=!0);void 0===a.showPermalinks&&(a.showPermalinks=!0);void 0===a.dataOnly&&(a.dataOnly=!1);if(B)z.push(a);else{B=!0;H=a.domId;m=a.maxTweets;J=a.enableLinks;r=a.showUser;C=a.showTime;F=a.showRetweet;D=a.dateFunction;A=a.customCallback;K=a.showInteraction;v=a.showImages;L=a.useEmoji;w=a.linksInNewWindow;M=a.showPermalinks;N=a.dataOnly;var h=document.getElementsByTagName("head")[0];
null!==n&&h.removeChild(n);n=document.createElement("script");n.type="text/javascript";n.src=void 0!==a.list?"https://syndication.twitter.com/timeline/list?callback=__twttrf.callback&dnt=false&list_slug="+a.list.listSlug+"&screen_name="+a.list.screenName+"&suppress_response_codes=true&lang="+(a.lang||"en")+"&rnd="+Math.random():void 0!==a.profile?"https://syndication.twitter.com/timeline/profile?callback=__twttrf.callback&dnt=false&screen_name="+a.profile.screenName+"&suppress_response_codes=true&lang="+
(a.lang||"en")+"&rnd="+Math.random():void 0!==a.likes?"https://syndication.twitter.com/timeline/likes?callback=__twttrf.callback&dnt=false&screen_name="+a.likes.screenName+"&suppress_response_codes=true&lang="+(a.lang||"en")+"&rnd="+Math.random():void 0!==a.collection?"https://syndication.twitter.com/timeline/collection?callback=__twttrf.callback&dnt=false&collection_id="+a.collection.collectionId+"&suppress_response_codes=true&lang="+(a.lang||"en")+"&rnd="+Math.random():"https://cdn.syndication.twimg.com/widgets/timelines/"+
a.id+"?&lang="+(a.lang||"en")+"&callback=__twttrf.callback&suppress_response_codes=true&rnd="+Math.random();h.appendChild(n)}},callback:function(a){function h(a){var b=a.getElementsByTagName("img")[0];if(b)b.src=b.getAttribute("data-src-1x");else{b=a.getElementsByTagName("a")[0].getAttribute("href").split("twitter.com/")[1];var c=document.createElement("img");c.setAttribute("src","https://twitter.com/"+b+"/profile_image?size=bigger");a.prepend(c)}return a}if(void 0!==a&&void 0!==a.body){L||(a.body=
a.body.replace(/(<img[^c]*class="Emoji[^>]*>)|(<img[^c]*class="u-block[^>]*>)/g,""));v||(a.body=a.body.replace(/(<img[^c]*class="NaturalImage-image[^>]*>|(<img[^c]*class="CroppedImage-image[^>]*>))/g,""));r||(a.body=a.body.replace(/(<img[^c]*class="Avatar"[^>]*>)/g,""));var c=document.createElement("div");c.innerHTML=a.body;"undefined"===typeof c.getElementsByClassName&&(E=!1);a=[];var f=[],g=[],k=[],d=[],n=[],t=[],e=0;if(E)for(c=c.getElementsByClassName("timeline-Tweet");e<c.length;){0<c[e].getElementsByClassName("timeline-Tweet-retweetCredit").length?
d.push(!0):d.push(!1);if(!d[e]||d[e]&&F)a.push(c[e].getElementsByClassName("timeline-Tweet-text")[0]),n.push(c[e].getAttribute("data-tweet-id")),r&&f.push(h(c[e].getElementsByClassName("timeline-Tweet-author")[0])),g.push(c[e].getElementsByClassName("dt-updated")[0]),t.push(c[e].getElementsByClassName("timeline-Tweet-timestamp")[0]),void 0!==c[e].getElementsByClassName("timeline-Tweet-media")[0]?k.push(c[e].getElementsByClassName("timeline-Tweet-media")[0]):k.push(void 0);e++}else for(c=p(c,"timeline-Tweet");e<
c.length;){0<p(c[e],"timeline-Tweet-retweetCredit").length?d.push(!0):d.push(!1);if(!d[e]||d[e]&&F)a.push(p(c[e],"timeline-Tweet-text")[0]),n.push(c[e].getAttribute("data-tweet-id")),r&&f.push(h(p(c[e],"timeline-Tweet-author")[0])),g.push(p(c[e],"dt-updated")[0]),t.push(p(c[e],"timeline-Tweet-timestamp")[0]),void 0!==p(c[e],"timeline-Tweet-media")[0]?k.push(p(c[e],"timeline-Tweet-media")[0]):k.push(void 0);e++}a.length>m&&(a.splice(m,a.length-m),f.splice(m,f.length-m),g.splice(m,g.length-m),d.splice(m,
d.length-m),k.splice(m,k.length-m),t.splice(m,t.length-m));c=[];e=a.length;var b=0;if(N)for(;b<e;)c.push({tweet:a[b].innerHTML,author:f[b]?f[b].innerHTML:"Unknown Author",author_data:{profile_url:f[b]?f[b].querySelector('[data-scribe="element:user_link"]').href:null,profile_image:f[b]?"https://twitter.com/"+f[b].querySelector('[data-scribe="element:screen_name"]').title.split("@")[1]+"/profile_image?size=bigger":null,profile_image_2x:f[b]?"https://twitter.com/"+f[b].querySelector('[data-scribe="element:screen_name"]').title.split("@")[1]+
"/profile_image?size=original":null,screen_name:f[b]?f[b].querySelector('[data-scribe="element:screen_name"]').title:null,name:f[b]?f[b].querySelector('[data-scribe="element:name"]').title:null},time:g[b].textContent,timestamp:g[b].getAttribute("datetime").replace("+0000","Z").replace(/([\+\-])(\d\d)(\d\d)/,"$1$2:$3"),image:u(k[b])?u(k[b])[0]:void 0,images:u(k[b]),rt:d[b],tid:n[b],permalinkURL:void 0===t[b]?"":t[b].href}),b++;else for(;b<e;){if("string"!==typeof D){d=g[b].getAttribute("datetime");
var q=new Date(g[b].getAttribute("datetime").replace(/-/g,"/").replace("T"," ").split("+")[0]);d=D(q,d);g[b].setAttribute("aria-label",d);if(a[b].textContent)if(E)g[b].textContent=d;else{q=document.createElement("p");var x=document.createTextNode(d);q.appendChild(x);q.setAttribute("aria-label",d);g[b]=q}else g[b].textContent=d}d="";J?(w&&(I(a[b]),r&&I(f[b])),r&&(d+='<div class="user">'+l(f[b].innerHTML)+"</div>"),d+='<p class="tweet">'+l(a[b].innerHTML)+"</p>",C&&(d=M?d+('<p class="timePosted"><a href="'+
t[b]+'">'+g[b].getAttribute("aria-label")+"</a></p>"):d+('<p class="timePosted">'+g[b].getAttribute("aria-label")+"</p>"))):(r&&(d+='<p class="user">'+f[b].textContent+"</p>"),d+='<p class="tweet">'+a[b].textContent+"</p>",C&&(d+='<p class="timePosted">'+g[b].textContent+"</p>"));K&&(d+='<p class="interact"><a href="https://twitter.com/intent/tweet?in_reply_to='+n[b]+'" class="twitter_reply_icon"'+(w?' target="_blank" rel="noopener">':">")+'Reply</a><a href="https://twitter.com/intent/retweet?tweet_id='+
n[b]+'" class="twitter_retweet_icon"'+(w?' target="_blank" rel="noopener">':">")+'Retweet</a><a href="https://twitter.com/intent/favorite?tweet_id='+n[b]+'" class="twitter_fav_icon"'+(w?' target="_blank" rel="noopener">':">")+"Favorite</a></p>");if(v&&void 0!==k[b]&&void 0!==u(k[b])&&(q=u(k[b])))for(x=0;x<q.length;x++)d+='<div class="media"><img src="'+q[x]+'" alt="Image from tweet" /></div>';v?c.push(d):!v&&a[b].textContent.length&&c.push(d);b++}y(c)}B=!1;0<z.length&&(G.fetch(z[0]),z.splice(0,1))}};
window.__twttrf=G;return window.twitterFetcher=G});(function(y){y.forEach(function(l){l.hasOwnProperty("prepend")||Object.defineProperty(l,"prepend",{configurable:!0,enumerable:!0,writable:!0,value:function(){var l=Array.prototype.slice.call(arguments),p=document.createDocumentFragment();l.forEach(function(l){p.appendChild(l instanceof Node?l:document.createTextNode(String(l)))});this.insertBefore(p,this.firstChild)}})})})([Element.prototype,Document.prototype,DocumentFragment.prototype]);
